# Generated by Django 5.2.8 on 2025-12-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_day_rate', models.IntegerField()),
                ('half_day_rate', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civil_app.department')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civil_app.site')),
            ],
        ),
    ]
