# Generated by Django 5.2.8 on 2025-12-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0002_defaultrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamrate',
            old_name='full_day_rate',
            new_name='helper_full_rate',
        ),
        migrations.RenameField(
            model_name='teamrate',
            old_name='half_day_rate',
            new_name='helper_half_rate',
        ),
        migrations.RemoveField(
            model_name='civildailywork',
            name='full_day_count',
        ),
        migrations.RemoveField(
            model_name='civildailywork',
            name='half_day_count',
        ),
        migrations.AddField(
            model_name='civildailywork',
            name='helper_full',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civildailywork',
            name='helper_half',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civildailywork',
            name='labour_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civildailywork',
            name='mason_full',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civildailywork',
            name='mason_half',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civildailywork',
            name='material_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamrate',
            name='mason_full_rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamrate',
            name='mason_half_rate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
