# Generated by Django 5.2.8 on 2025-12-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0003_rename_full_day_rate_teamrate_helper_full_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultrate',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamrate',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
