# Generated by Django 5.2.8 on 2025-12-15 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0004_defaultrate_is_locked_teamrate_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='department',
        ),
        migrations.AddField(
            model_name='civildailywork',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='civil_app.site'),
            preserve_default=False,
        ),
    ]
