# Generated by Django 5.2.8 on 2025-12-15 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0005_remove_team_department_civildailywork_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultrate',
            name='site',
        ),
        migrations.AlterField(
            model_name='defaultrate',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='civil_app.department'),
        ),
    ]
