# Generated by Django 5.2.8 on 2025-12-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0006_remove_defaultrate_site_alter_defaultrate_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultrate',
            name='half_day_rate',
        ),
    ]
