# Generated by Django 5.2.8 on 2025-12-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0007_remove_defaultrate_half_day_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrate',
            name='helper_half_rate',
        ),
        migrations.RemoveField(
            model_name='teamrate',
            name='mason_half_rate',
        ),
    ]
