# Generated by Django 5.2.8 on 2025-12-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0008_remove_teamrate_helper_half_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentwork',
            name='labour_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='departmentwork',
            name='material_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defaultrate',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='departmentwork',
            name='full_day_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='departmentwork',
            name='half_day_count',
            field=models.IntegerField(default=0),
        ),
    ]
