# Generated by Django 5.2.8 on 2025-12-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0009_departmentwork_labour_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultrate',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamrate',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
