# Generated by Django 5.2.8 on 2025-12-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0010_defaultrate_effective_from_teamrate_effective_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='site',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
