# Generated by Django 5.2.8 on 2025-12-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0011_remove_department_site_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultrate',
            name='full_day_rate',
            field=models.IntegerField(default=0),
        ),
    ]
