# Generated by Django 5.2.8 on 2025-12-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0012_alter_defaultrate_full_day_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='civildailywork',
            unique_together={('site', 'team', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='departmentwork',
            unique_together={('department', 'date')},
        ),
    ]
