# Generated by Django 5.2.8 on 2025-12-16 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0013_alter_civildailywork_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentwork',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='civil_app.site'),
            preserve_default=False,
        ),
    ]
