# Generated by Django 5.2.8 on 2025-12-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0014_departmentwork_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentwork',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_works', to='civil_app.site'),
        ),
    ]
