# Generated by Django 5.2.8 on 2025-12-17 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0015_alter_departmentwork_site'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentwork',
            unique_together={('site', 'department', 'date')},
        ),
    ]
