# Generated by Django 5.2.8 on 2025-12-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0016_alter_departmentwork_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.PositiveIntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civil_app.site')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civil_app.team')),
            ],
            options={
                'unique_together': {('site', 'team', 'date')},
            },
        ),
    ]
