# Generated by Django 5.2.8 on 2025-12-25 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0017_civiladvance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmaterial',
            name='department',
        ),
        migrations.CreateModel(
            name='MaterialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('total', models.FloatField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civil_app.site')),
            ],
        ),
        migrations.DeleteModel(
            name='CivilMaterial',
        ),
        migrations.DeleteModel(
            name='DepartmentMaterial',
        ),
    ]
