# Generated by Django 5.2.8 on 2025-12-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0018_remove_departmentmaterial_department_materialentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civildailywork',
            name='material_amount',
        ),
        migrations.AddField(
            model_name='civildailywork',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
