# Generated by Django 5.2.8 on 2025-12-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0020_deptadvance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentwork',
            name='material_amount',
        ),
        migrations.AddField(
            model_name='departmentwork',
            name='advance_amount',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='DeptAdvance',
        ),
    ]
