# Generated by Django 5.2.8 on 2025-12-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0021_remove_departmentwork_material_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentwork',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
