# Generated by Django 5.2.8 on 2025-12-28 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0022_departmentwork_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialentry',
            name='agentname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
