# Generated by Django 5.2.8 on 2025-12-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0023_materialentry_agentname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialentry',
            old_name='agentname',
            new_name='agent_name',
        ),
    ]
