# Generated by Django 5.2.8 on 2026-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0024_rename_agentname_materialentry_agent_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=20)),
                ('reference', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('paid_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='materialentry',
            name='advance',
            field=models.FloatField(default=0),
        ),
    ]
