# Generated by Django 5.2.8 on 2026-02-18 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0025_billpayment_materialentry_advance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDailyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civil_app.site')),
            ],
            options={
                'unique_together': {('site', 'date')},
            },
        ),
    ]
