# Generated by Django 5.2.8 on 2026-02-24 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0028_owner_otherexpense_owner_ownercashentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otherexpense',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='otherexpense',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='civil_app.ownercashentry'),
        ),
        migrations.RemoveField(
            model_name='otherexpense',
            name='description',
        ),
    ]
