# Generated by Django 5.2.8 on 2026-03-01 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0029_alter_otherexpense_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='otherexpense',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='civil_app.owner'),
        ),
    ]
