# Generated by Django 5.2.8 on 2026-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0030_site_owner_alter_otherexpense_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civiladvance',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
