# Generated by Django 5.2.8 on 2026-03-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0031_alter_civiladvance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='civildailywork',
            name='allowance_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='civildailywork',
            name='extra_allowance',
            field=models.FloatField(default=0),
        ),
    ]
