# Generated by Django 5.2.8 on 2026-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0032_civildailywork_allowance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civildailywork',
            name='advance_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='civildailywork',
            name='labour_amount',
            field=models.FloatField(default=0),
        ),
    ]
