# Generated by Django 5.2.8 on 2026-09-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_app', '0033_civildailywork_advance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civildailywork',
            name='helper_full',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='civildailywork',
            name='helper_half',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='civildailywork',
            name='mason_full',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='civildailywork',
            name='mason_half',
            field=models.FloatField(default=0),
        ),
    ]
